### ISSUE TITLE
How can I edit grub after installation?

### ISSUE THREAD

**Issue by yangxuan8282** [ExtremeGTX/Androidx86-Installer-for-Windows#12]
I have successful installed android x86 system with the installer. It works.
After that, I am trying to install another android x86 OS on my disk,but can't find **grub.cfg**,or **/boot** folder.
Can you help me?

By the way, would you support Remix OS in the future,since it's optimized for desktop.

**Comment by ExtremeGTX** [comment]
GRUB must be installed to EFI partition so firmware can load grub.efi binary
to Access the EFI partition from windows:

Launch cmd as Admin and type the following commands:
taskkill /f /im explorer.exe
mountvol z: /s
explorer.exe

**Comment by yangxuan8282** [comment]
@ExtremeGTX Thanks,I have found the **grub.cfg** follow your guide.
