### ISSUE TITLE
Edit boot configure during installation?

### ISSUE THREAD

**Issue by yangxuan8282** [ExtremeGTX/Androidx86-Installer-for-Windows#13]
The new release is much better than the official RemixOS installer, since this installer come with NTFS support and User-defined Data size feature.
Can you add a 'Edit Bootloader' button? This maybe not necessary for most Android x86 user, they installation will work without problem. But  for remixos user, they have to do some change with _grub.cfg_.Otherwise the system won't boot.Such as replace **--set=root /AndroidOS/android.boot** with **--set=root /AndroidOS/system.sfs**, replace **androidboot.hardware=android_x86_64** with **androidboot.hardware=remix_cn_x86_64**.
I know there is method to edit bootloader configure file before or after installation, but it's not very convenient.

**Comment by ExtremeGTX** [comment]
/AndroidOS/android.boot is created to help GRUB find the installation of android or remix os, nothing to do with system booting.

can you tell me what's version includes hardware **remix_cn_x86_64** ? version B2016012301 still use **remix_x86_64**.

BTW, 'Edit Boot Config' will be included in the next major releas

**Comment by yangxuan8282** [comment]
@ExtremeGTX Thanks for reply. I have tried keep **--set=root /AndroidOS/android.boot** in _grub. cfg_, but got booting failed, it just reboot to grub.
As for **androidboot.hardware**, I am downloading the system image from Chinese version official site, so maybe there are difference between Chinese version and international version.Do you think it is possible that let the installer read boot config from system image and auto generate boot configure file?
