### ISSUE TITLE
What should I do now?

### ISSUE THREAD

**Issue by Roseclear** [ExtremeGTX/Androidx86-Installer-for-Windows#32]
================Installer Info================
Installer Directory:C:\Users\chilo\AppData\Local\Temp\droidinst_efi
Installer Version:2.4.5800.0
Secure Boot ... Disabled
Manufacturer: Acer
Model: Aspire A315-56
Product: Sleepy_IL
BIOS info:
ACRSYS - 2
V1.22
INSYDE Corp. - 59115122
Available GPU(s):
GPU: Intel(R) UHD Graphics
=============[REQUIREMENTS CHECK]============
Administrator privilege ... ok
CPU Architecture: 9
CPU Name: Intel(R) Core(TM) i3-1005G1 CPU @ 1.20GHz
OSVer: Microsoft Windows NT 10.0.22621.0
OperatingSystem Version ... ok
Windows Security: Access NVRAM Privilege ... Not All Set
System Firmware: UEFI
==========================================
====Install Started on 20/01/2023 16:20:11====
-ISO File: D:\BlissOS\Bliss-v11.14--OFFICIAL-20210508-1013_x86_64_k-k4.19.122-ax86-ga-rmi_m-20.1.10_pie-x86_dgc-p9.0-11.13_ld-p9.0-x86_dg-_dh-blueprint_pie-x86_w45_2020_mg-p9.0-x86.iso
-TargetDrive: E
-UserData: 33470546
-Setup Directories...
-Folder Created: E:\AndroidOS
-Extract ISO
#Launch:C:\Users\chilo\AppData\Local\Temp\droidinst_efi\7z.exe x "D:\BlissOS\Bliss-v11.14--OFFICIAL-20210508-1013_x86_64_k-k4.19.122-ax86-ga-rmi_m-20.1.10_pie-x86_dgc-p9.0-11.13_ld-p9.0-x86_dg-_dh-blueprint_pie-x86_w45_2020_mg-p9.0-x86.iso" "kernel" "ramdisk.img" "initrd.img" "system.*" -oE:\AndroidOS
-Extract SFS
#Launch:C:\Users\chilo\AppData\Local\Temp\droidinst_efi\7z.exe x E:\AndroidOS\system.sfs "system.img" -oE:\AndroidOS
#Launch:C:\Users\chilo\AppData\Local\Temp\droidinst_efi\7z.exe e "D:\BlissOS\Bliss-v11.14--OFFICIAL-20210508-1013_x86_64_k-k4.19.122-ax86-ga-rmi_m-20.1.10_pie-x86_dgc-p9.0-11.13_ld-p9.0-x86_dg-_dh-blueprint_pie-x86_w45_2020_mg-p9.0-x86.iso" "efi\boot\grub.cfg" -oE:\AndroidOS
==============Revert Installation==============
-Cleaning up Android Directory ... E:\AndroidOS
===Removing Boot Objects===
-Mounting EFI Partition...
#Launch:C:\Windows\System32\mountvol.exe Z: /S
-Remove Android UEFI Entry
-UEFI: -1
-Cleaning up Android Directory ... Z:\EFI\Android\
-UnMounting EFI Partition...
#Launch:C:\Windows\System32\mountvol.exe Z: /D
==========================================
====Install Started on 20/01/2023 16:24:18====
-ISO File: D:\BlissOS\Bliss-v11.14--OFFICIAL-20210508-1013_x86_64_k-k4.19.122-ax86-ga-rmi_m-20.1.10_pie-x86_dgc-p9.0-11.13_ld-p9.0-x86_dg-_dh-blueprint_pie-x86_w45_2020_mg-p9.0-x86.iso
-TargetDrive: E
-UserData: 33470546
-Setup Directories...
-Folder Created: E:\AndroidOS
-Extract ISO
#Launch:C:\Users\chilo\AppData\Local\Temp\droidinst_efi\7z.exe x "D:\BlissOS\Bliss-v11.14--OFFICIAL-20210508-1013_x86_64_k-k4.19.122-ax86-ga-rmi_m-20.1.10_pie-x86_dgc-p9.0-11.13_ld-p9.0-x86_dg-_dh-blueprint_pie-x86_w45_2020_mg-p9.0-x86.iso" "kernel" "ramdisk.img" "initrd.img" "system.*" -oE:\AndroidOS
-Extract SFS
#Launch:C:\Users\chilo\AppData\Local\Temp\droidinst_efi\7z.exe x E:\AndroidOS\system.sfs "system.img" -oE:\AndroidOS
#Launch:C:\Users\chilo\AppData\Local\Temp\droidinst_efi\7z.exe e "D:\BlissOS\Bliss-v11.14--OFFICIAL-20210508-1013_x86_64_k-k4.19.122-ax86-ga-rmi_m-20.1.10_pie-x86_dgc-p9.0-11.13_ld-p9.0-x86_dg-_dh-blueprint_pie-x86_w45_2020_mg-p9.0-x86.iso" "efi\boot\grub.cfg" -oE:\AndroidOS
==============Revert Installation==============
-Cleaning up Android Directory ... E:\AndroidOS
===Removing Boot Objects===
-Mounting EFI Partition...
#Launch:C:\Windows\System32\mountvol.exe Z: /S
-Remove Android UEFI Entry
-UEFI: -1
-Cleaning up Android Directory ... Z:\EFI\Android\
-UnMounting EFI Partition...
#Launch:C:\Windows\System32\mountvol.exe Z: /D
==========================================
====Uninstall Started on 20/01/2023 16:27:19====
Android Installation Not Found
===Removing Boot Objects===
-Mounting EFI Partition...
#Launch:C:\Windows\System32\mountvol.exe Z: /S
-Remove Android UEFI Entry
-UEFI: -1
-Cleaning up Android Directory ... Z:\EFI\Android\
-UnMounting EFI Partition...
#Launch:C:\Windows\System32\mountvol.exe Z: /D
==========================================

**Comment by ExtremeGTX** [comment]
it has been a while since I maintained this project, unfortunately it is not compatible any more with latest builds of Android-x86 or BlissOS.

Please have a look here: [Bliss OS - Install from Windows](https://docs.blissos.org/installation/install-from-windows-uefi-esp-64-bit/#install-from-windows---uefiesp-64-bit)
