### ISSUE TITLE
Virtual SIM

### ISSUE THREAD

**Issue by pistolwhip-justin** [ExtremeGTX/Androidx86-Installer-for-Windows#34]
I have no idea if possible, but would be nice if BlissOS could support virtual SIMs so a phone number could be used in the OS for certain app functionality.

Just a suggestion, close issue.

**Comment by ExtremeGTX** [comment]
That would be great, but please open an issue there or send them an email so your suggestion get better visibility.
This project is just about OS Installation.
Have a good day :)
